# ===============================
# Increase Gradle performance
# ===============================

# Use more RAM for faster builds
org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC

# Enable parallel project execution
org.gradle.parallel=true

# Enable configuration on demand
org.gradle.configureondemand=true

# Reuse classpath structure for faster incremental builds
org.gradle.caching=true

# Use AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin incremental builds
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true
kotlin.incremental.useClasspathSnapshot=true

# Enable Gradle daemon
org.gradle.daemon=true

# Enable incremental dexing
android.enableDexingArtifactTransform=true

# Faster resource merging
android.nonTransitiveRClass=true


# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
